
# Site settings
title:          dueilee0
description:    ""
baseurl:        ""
url:            "https://dueilee0.github.io"

# Author
author:
  name:         dueilee0
  url:          https://dueilee0.github.io
  email:        dueilee0@naver.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:      /posts/:title
paginate:       5

social_links:
  twitter: 
  github: dueilee0
  linkedIn: 
  rss: rss

texture:
  title: dueilee0
  tagline: 
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false
