
# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            "https://dueilee0.github.io"

# Author
author:
  name:         dueilee0
  url:          https://dueilee0.github.io
  email:        dueilee0@naver.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:      /posts/:title
paginate:       5

social_links:
  twitter: thelehhman
  github:  thelehhman
  linkedIn: in/thelehhman
  rss: rss

texture:
  title: Adam Denisov
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false
